// Auto-generated by shader-precompile --emit-index — do not edit
/// <reference path="./global.d.ts" />
import OutlinePostprocessSource from "./OutlinePostprocess.gsp";
import OutlineReplaceSource from "./OutlineReplace.gsp";

// prettier-ignore
export {
  OutlinePostprocessSource,
  OutlineReplaceSource
};
