// Auto-generated by shader-precompile --emit-index — do not edit
/// <reference path="./global.d.ts" />
import BoxSelectionSource from "./box-selection/BoxSelection.gsp";

// prettier-ignore
export {
  BoxSelectionSource
};
