// Auto-generated by shader-compiler-precompile --emit-index — do not edit.
import OutlinePostprocessSource from "./OutlinePostprocess.shaderc";
import OutlineReplaceSource from "./OutlineReplace.shaderc";

// prettier-ignore
export {
  OutlinePostprocessSource,
  OutlineReplaceSource
};
