// Auto-generated by shader-compiler-precompile --emit-index — do not edit.
import TBNSource from "./material/TBN.shaderc";
import WireframeSource from "./material/Wireframe.shaderc";

// prettier-ignore
export {
  TBNSource,
  WireframeSource
};
