// Auto-generated by shader-compiler-precompile --emit-index — do not edit.
import BoxSelectionSource from "./box-selection/BoxSelection.shaderc";

// prettier-ignore
export {
  BoxSelectionSource
};
