// Auto-generated by shader-compiler-precompile --emit-index — do not edit.
import DashSource from "./line/material/Dash.shaderc";
import LineSource from "./line/material/Line.shaderc";

// prettier-ignore
export {
  DashSource,
  LineSource
};
