// Auto-generated by shader-precompile --emit-index — do not edit
/// <reference path="./global.d.ts" />
import BakePBRSource from "./bake-pbr/BakePBR.gsp";
import EyeSource from "./advanced-shader/eye/Eye.gsp";
import GridSource from "./grid/Grid.gsp";
import HairSource from "./advanced-shader/hair/Hair.gsp";
import PlainColorSource from "./plain-color/PlainColor.gsp";
import PlanarShadowOnlySource from "./planar-shadow/PlanarShadowOnly.gsp";
import PlanarShadowSource from "./planar-shadow/PlanarShadow.gsp";
import SSSSource from "./advanced-shader/sss/SSS.gsp";
import WaterFallSource from "./water/WaterFall.gsp";
import WaterRippleSource from "./water/WaterRipple.gsp";
import WaterSource from "./water/Water.gsp";

// prettier-ignore
export {
  BakePBRSource,
  EyeSource,
  GridSource,
  HairSource,
  PlainColorSource,
  PlanarShadowOnlySource,
  PlanarShadowSource,
  SSSSource,
  WaterFallSource,
  WaterRippleSource,
  WaterSource
};
