// Auto-generated by shader-precompile --emit-index — do not edit
import TBNSource from "./material/TBN.gsp";
import WireframeSource from "./material/Wireframe.gsp";

// prettier-ignore
export {
  TBNSource,
  WireframeSource
};
