// Auto-generated by shader-precompile --emit-index — do not edit
/// <reference path="./global.d.ts" />
import TBNSource from "./material/TBN.gsp";
import WireframeSource from "./material/Wireframe.gsp";

// prettier-ignore
export {
  TBNSource,
  WireframeSource
};
