// Auto-generated by shader-precompile --emit-index — do not edit
/// <reference path="./global.d.ts" />
import SkeletonViewerSource from "./SkeletonViewer.gsp";

// prettier-ignore
export {
  SkeletonViewerSource
};
