// Auto-generated by shader-precompile --emit-index — do not edit
/// <reference path="./global.d.ts" />
import DashSource from "./line/material/Dash.gsp";
import LineSource from "./line/material/Line.gsp";

// prettier-ignore
export {
  DashSource,
  LineSource
};
