// Auto-generated by shader-precompile --emit-index — do not edit
import DashSource from "./line/material/Dash.gsp";
import LineSource from "./line/material/Line.gsp";

export {
  DashSource,
  LineSource
};
