// Auto-generated by shader-compiler-precompile --emit-index — do not edit.
import FramebufferPickerColorSource from "./FramebufferPickerColor.shaderc";

// prettier-ignore
export {
  FramebufferPickerColorSource
};
