// Auto-generated by shader-precompile --emit-index — do not edit
/// <reference path="./global.d.ts" />
import FramebufferPickerColorSource from "./FramebufferPickerColor.gsp";

// prettier-ignore
export {
  FramebufferPickerColorSource
};
