// Auto-generated by shader-precompile --emit-index — do not edit
import FramebufferPickerColorSource from "./FramebufferPickerColor.gsp";

// prettier-ignore
export {
  FramebufferPickerColorSource
};
